
'use server';

import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { webSearch } from './web-search';
import { googleAI } from '@genkit-ai/googleai';
import wav from 'wav';

// Define the input schema
const ConversationalVoiceResponseInputSchema = z.object({
  history: z.array(z.object({
    role: z.string(),
    content: z.string(),
  })),
  persona: z.string(),
});
export type ConversationalVoiceResponseInput = z.infer<typeof ConversationalVoiceResponseInputSchema>;

// Define the output schema
const ConversationalVoiceResponseOutputSchema = z.object({
  response: z.string(),
  audio: z.string(), // Base64 encoded WAV audio
});
export type ConversationalVoiceResponseOutput = z.infer<typeof ConversationalVoiceResponseOutputSchema>;

// Helper function to convert PCM audio buffer to WAV format
async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    const bufs: any[] = [];
    writer.on('error', reject);
    writer.on('data', (d) => bufs.push(d));
    writer.on('end', () => resolve(Buffer.concat(bufs).toString('base64')));

    writer.write(pcmData);
    writer.end();
  });
}

export const conversationalVoiceResponse = ai.defineFlow(
  {
    name: 'conversationalVoiceResponse',
    inputSchema: ConversationalVoiceResponseInputSchema,
    outputSchema: ConversationalVoiceResponseOutputSchema,
  },
  async (input) => {
    const { history, persona } = input;
    const userPrompt = history[history.length - 1]?.content || '';

    // Step 1: Generate the text response
    const textGenerationResponse = await ai.generate({
      prompt: `You are an AI assistant with a specific persona: ${persona}. 
      Your conversation history with the user is as follows:
      ${JSON.stringify(history)}

      You have access to a tool called 'webSearch' that can search the internet for real-time information.

      **CRITICAL INSTRUCTION:** You must decide whether to use your internal knowledge or the 'webSearch' tool based on these rules:

      1.  **Use the 'webSearch' tool ONLY for these specific cases:**
          *   If the user explicitly asks you to search the web (e.g., "search for...", "look up...", "find information on...").
          *   For queries about news, current events, stock prices, weather, or other topics that require real-time, up-to-the-minute information.
          *   For questions about recent developments or public figures where information is likely to have changed.

      2.  **For ALL OTHER queries, you MUST use your internal knowledge.**

      Based on the latest user prompt ("${userPrompt}"), generate a helpful and conversational response that is consistent with your persona.`,
      model: 'googleai/gemini-1.5-flash-latest',
      tools: [webSearch],
    });
    
    const textResponse = textGenerationResponse.text;
    
    // Step 2: Generate audio from the text response
    const ttsResponse = await ai.generate({
      model: googleAI.model('gemini-2.5-flash-preview-tts'),
      prompt: textResponse,
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: 'Algenib' }, // Example voice
          },
        },
      },
    });

    const audioMedia = ttsResponse.media;
    if (!audioMedia) {
      throw new Error('No audio media was generated by the TTS model.');
    }

    // The media URL is a base64 encoded data URI for PCM audio
    const pcmAudioBuffer = Buffer.from(
      audioMedia.url.substring(audioMedia.url.indexOf(',') + 1),
      'base64'
    );
    
    // Convert PCM to WAV
    const wavAudioBase64 = await toWav(pcmAudioBuffer);
    
    return { 
      response: textResponse,
      audio: wavAudioBase64
    };
  }
);
