'use server';

/**
 * @fileOverview A persona-based response AI agent.
 *
 * - personaBasedResponse - A function that generates a response based on a selected persona.
 * - PersonaBasedResponseInput - The input type for the personaBasedResponse function.
 * - PersonaBasedResponseOutput - The return type for the personaBasedResponse function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'zod';

const PersonaBasedResponseInputSchema = z.object({
  persona: z
    .string()
    .describe(
      'The persona to use for the response (e.g., Friend, Teacher, Spiritual, Pro, Storyteller).'
    ),
  prompt: z.string().describe('The user prompt to respond to.'),
});
export type PersonaBasedResponseInput = z.infer<typeof PersonaBasedResponseInputSchema>;

const PersonaBasedResponseOutputSchema = z.object({
  response: z.string().describe('The response generated by the AI with the given persona.'),
});
export type PersonaBasedResponseOutput = z.infer<typeof PersonaBasedResponseOutputSchema>;

export async function personaBasedResponse(input: PersonaBasedResponseInput): Promise<PersonaBasedResponseOutput> {
  return personaBasedResponseFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personaBasedResponsePrompt',
  input: {schema: PersonaBasedResponseInputSchema},
  output: {schema: PersonaBasedResponseOutputSchema},
  prompt: `You are an AI assistant that responds to user prompts with a specific persona.

Your persona is: {{{persona}}}

User prompt: {{{prompt}}}

Response:`, // No Handlebars template for complex formatting or logic
});

const personaBasedResponseFlow = ai.defineFlow(
  {
    name: 'personaBasedResponseFlow',
    inputSchema: PersonaBasedResponseInputSchema,
    outputSchema: PersonaBasedResponseOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
